[package]
name = "skillet"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "skillet"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
walkdir = "2"
anyhow = "1"
regex = "1.12.3"
sha2 = "0.11.0"
hex = "0.4.3"
chrono = { version = "0.4.44", features = ["serde"] }

[dev-dependencies]
tempfile = "3"

[lints.rust]
missing_docs = "warn"

[profile.release]
lto = "thin"
strip = true
