//! Generation and persistence of `skillet.lock`.

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

const LOCK_HEADER: &str =
    "# Auto-generated by skillet build. Do not edit. Run `skillet check` to verify freshness.\n\n";

/// Top-level metadata recorded on each build.
#[non_exhaustive]
#[derive(Debug, Serialize, Deserialize)]
pub struct LockMeta {
    /// Skillet version that produced this lockfile.
    pub skillet_version: String,
    /// RFC 3339 timestamp of the build.
    pub built_at: DateTime<Utc>,
    /// Tokenizer used for budget calculations.
    pub tokenizer: String,
}

/// Per-skill entry in the lockfile.
#[non_exhaustive]
#[derive(Debug, Serialize, Deserialize)]
pub struct SkillEntry {
    /// SHA-256 hex digest of the `.skill` source file.
    pub source_hash: String,
    /// SHA-256 hex digest of the compiled `SKILL.md` output.
    pub compiled_hash: String,
    /// Names of fragments inlined during compilation.
    pub fragments_used: Vec<String>,
}

/// The full contents of `skillet.lock`.
#[non_exhaustive]
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Lockfile {
    /// Build metadata, set on every successful build.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<LockMeta>,
    /// Per-skill entries, keyed by skill name.
    #[serde(default)]
    pub skills: BTreeMap<String, SkillEntry>,
}

/// Reads `skillet.lock` from `workspace`, returning a default if it doesn't exist.
pub fn read(workspace: &Path) -> Result<Lockfile> {
    let path = workspace.join("skillet.lock");
    if !path.exists() {
        return Ok(Lockfile::default());
    }
    let raw = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    // Strip comment lines before TOML parsing
    let stripped: String = raw
        .lines()
        .filter(|l| !l.starts_with('#'))
        .flat_map(|l| [l, "\n"])
        .collect();
    toml::from_str(&stripped).context("failed to parse skillet.lock")
}

/// Writes `lockfile` to `<workspace>/skillet.lock`.
pub fn write(workspace: &Path, lockfile: &Lockfile) -> Result<()> {
    let path = workspace.join("skillet.lock");
    let body = toml::to_string_pretty(lockfile).context("failed to serialize lockfile")?;
    std::fs::write(&path, format!("{}{}", LOCK_HEADER, body))
        .with_context(|| format!("failed to write {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_lockfile() -> Lockfile {
        let mut lf = Lockfile::default();
        lf.meta = Some(LockMeta {
            skillet_version: "0.1.0".into(),
            built_at: "2026-01-01T00:00:00Z".parse::<DateTime<Utc>>().unwrap(),
            tokenizer: "cl100k_base".into(),
        });
        lf.skills.insert(
            "diagnose".into(),
            SkillEntry {
                source_hash: "sha256:abc".into(),
                compiled_hash: "sha256:def".into(),
                fragments_used: vec!["check-adrs".into()],
            },
        );
        lf
    }

    #[test]
    fn write_then_read_round_trips_all_fields() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let original = make_lockfile();

        // Act
        write(tmp.path(), &original).unwrap();
        let loaded = read(tmp.path()).unwrap();

        // Assert
        let meta = loaded.meta.unwrap();
        assert_eq!(meta.skillet_version, "0.1.0");
        assert_eq!(meta.tokenizer, "cl100k_base");
        let skill = loaded.skills.get("diagnose").unwrap();
        assert_eq!(skill.source_hash, "sha256:abc");
        assert_eq!(skill.fragments_used, vec!["check-adrs"]);
    }

    #[test]
    fn write_produces_header_comment() {
        // Arrange
        let tmp = TempDir::new().unwrap();

        // Act
        write(tmp.path(), &Lockfile::default()).unwrap();
        let content = std::fs::read_to_string(tmp.path().join("skillet.lock")).unwrap();

        // Assert
        assert!(content.starts_with("# Auto-generated by skillet build"));
    }

    #[test]
    fn read_returns_default_when_lockfile_absent() {
        // Arrange
        let tmp = TempDir::new().unwrap();

        // Act
        let lf = read(tmp.path()).unwrap();

        // Assert
        assert!(lf.meta.is_none());
        assert!(lf.skills.is_empty());
    }
}
