//! Generation and persistence of `skillet.lock`.

use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

const LOCK_HEADER: &str =
    "# Auto-generated by skillet build. Do not edit. Run `skillet check` to verify freshness.\n\n";

/// Top-level metadata recorded on each build.
#[non_exhaustive]
#[derive(Debug, Serialize, Deserialize)]
pub struct LockMeta {
    /// Skillet version that produced this lockfile.
    pub skillet_version: String,
    /// RFC 3339 timestamp of the build.
    pub built_at: DateTime<Utc>,
    /// Tokenizer used for budget calculations.
    pub tokenizer: String,
}

/// Per-fragment entry in the lockfile.
#[non_exhaustive]
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct FragmentLockEntry {
    /// SHA-256 hex digest of the fragment source file.
    pub hash: String,
    /// Approximate token count for this fragment's source.
    #[serde(default)]
    pub tokens: u32,
    /// Skill names that include this fragment, sorted alphabetically.
    pub used_by: Vec<String>,
}

/// Structured per-skill refs recorded in the lockfile.
#[non_exhaustive]
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct SkillRefs {
    /// Markdown path link targets and `ref::` paths.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub paths: Vec<String>,
    /// `cmd::` command references.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub commands: Vec<String>,
    /// `skill::` cross-skill references.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub skills: Vec<String>,
    /// URL link targets (http/https).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub urls: Vec<String>,
}

impl SkillRefs {
    /// Returns `true` when all ref lists are empty.
    pub fn is_empty(&self) -> bool {
        self.paths.is_empty()
            && self.commands.is_empty()
            && self.skills.is_empty()
            && self.urls.is_empty()
    }
}

/// Per-skill entry in the lockfile.
#[non_exhaustive]
#[derive(Debug, Serialize, Deserialize)]
pub struct SkillEntry {
    /// SHA-256 hex digest of the `.skill` source file.
    pub source_hash: String,
    /// SHA-256 hex digest of the compiled `SKILL.md` output.
    pub compiled_hash: String,
    /// Tokens for `name` + `description` (discovery cost).
    #[serde(default)]
    pub discovery_tokens: u32,
    /// Tokens for the full compiled `SKILL.md` (activation cost).
    #[serde(default)]
    pub activation_tokens: u32,
    /// Activation tokens + tokens for files linked via `ref::` (transitive cost).
    #[serde(default)]
    pub transitive_tokens: u32,
    /// Names of fragments inlined during compilation.
    pub fragments_used: Vec<String>,
    /// Structured refs detected in the compiled output.
    #[serde(default, skip_serializing_if = "SkillRefs::is_empty")]
    pub refs: SkillRefs,
}

/// The full contents of `skillet.lock`.
#[non_exhaustive]
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Lockfile {
    /// Build metadata, set on every successful build.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<LockMeta>,
    /// Per-skill entries, keyed by skill name.
    #[serde(default)]
    pub skills: BTreeMap<String, SkillEntry>,
    /// Per-fragment entries, keyed by fragment name.
    /// Only present when at least one fragment is used.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub fragments: BTreeMap<String, FragmentLockEntry>,
}

/// Reads `skillet.lock` from `workspace`, returning a default if it doesn't exist.
pub fn read(workspace: &Path) -> Result<Lockfile> {
    let path = workspace.join("skillet.lock");
    if !path.exists() {
        return Ok(Lockfile::default());
    }
    let raw = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    // Strip comment lines before TOML parsing
    let stripped: String = raw
        .lines()
        .filter(|l| !l.starts_with('#'))
        .flat_map(|l| [l, "\n"])
        .collect();
    toml::from_str(&stripped).context("failed to parse skillet.lock")
}

/// Writes `lockfile` to `<workspace>/skillet.lock`.
pub fn write(workspace: &Path, lockfile: &Lockfile) -> Result<()> {
    let path = workspace.join("skillet.lock");
    let body = toml::to_string_pretty(lockfile).context("failed to serialize lockfile")?;
    std::fs::write(&path, format!("{}{}", LOCK_HEADER, body))
        .with_context(|| format!("failed to write {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_lockfile() -> Lockfile {
        let mut lf = Lockfile {
            meta: Some(LockMeta {
                skillet_version: "0.1.0".into(),
                built_at: "2026-01-01T00:00:00Z".parse::<DateTime<Utc>>().unwrap(),
                tokenizer: "cl100k_base".into(),
            }),
            ..Default::default()
        };
        lf.skills.insert(
            "diagnose".into(),
            SkillEntry {
                source_hash: "sha256:abc".into(),
                compiled_hash: "sha256:def".into(),
                discovery_tokens: 10,
                activation_tokens: 100,
                transitive_tokens: 150,
                fragments_used: vec!["check-adrs".into()],
                refs: SkillRefs {
                    commands: vec!["git".into()],
                    ..Default::default()
                },
            },
        );
        lf.fragments.insert(
            "check-adrs".into(),
            FragmentLockEntry {
                hash: "sha256:ff00".into(),
                tokens: 42,
                used_by: vec!["diagnose".into()],
            },
        );
        lf
    }

    #[test]
    fn write_then_read_round_trips_all_fields() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let original = make_lockfile();

        // Act
        write(tmp.path(), &original).unwrap();
        let loaded = read(tmp.path()).unwrap();

        // Assert
        let meta = loaded.meta.unwrap();
        assert_eq!(meta.skillet_version, "0.1.0");
        assert_eq!(meta.tokenizer, "cl100k_base");
        let skill = loaded.skills.get("diagnose").unwrap();
        assert_eq!(skill.source_hash, "sha256:abc");
        assert_eq!(skill.fragments_used, vec!["check-adrs"]);
        assert_eq!(skill.discovery_tokens, 10);
        assert_eq!(skill.activation_tokens, 100);
        assert_eq!(skill.transitive_tokens, 150);
        assert_eq!(skill.refs.commands, vec!["git"]);
        let frag = loaded.fragments.get("check-adrs").unwrap();
        assert_eq!(frag.hash, "sha256:ff00");
        assert_eq!(frag.tokens, 42);
        assert_eq!(frag.used_by, vec!["diagnose"]);
    }

    #[test]
    fn write_produces_header_comment() {
        // Arrange
        let tmp = TempDir::new().unwrap();

        // Act
        write(tmp.path(), &Lockfile::default()).unwrap();
        let content = std::fs::read_to_string(tmp.path().join("skillet.lock")).unwrap();

        // Assert
        assert!(content.starts_with("# Auto-generated by skillet build"));
    }

    #[test]
    fn fragments_section_omitted_when_empty() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let lf = Lockfile::default(); // no fragments

        // Act
        write(tmp.path(), &lf).unwrap();
        let content = std::fs::read_to_string(tmp.path().join("skillet.lock")).unwrap();

        // Assert
        assert!(
            !content.contains("[fragments]"),
            "fragments section should be omitted when empty"
        );
    }

    #[test]
    fn read_returns_default_when_lockfile_absent() {
        // Arrange
        let tmp = TempDir::new().unwrap();

        // Act
        let lf = read(tmp.path()).unwrap();

        // Assert
        assert!(lf.meta.is_none());
        assert!(lf.skills.is_empty());
    }

    #[test]
    fn write_then_read_preserves_token_fields_and_structured_refs() {
        // Arrange
        let tmp = TempDir::new().unwrap();
        let original = make_lockfile();

        // Act
        write(tmp.path(), &original).unwrap();
        let loaded = read(tmp.path()).unwrap();

        // Assert
        let skill = loaded.skills.get("diagnose").unwrap();
        assert_eq!(skill.discovery_tokens, 10);
        assert_eq!(skill.activation_tokens, 100);
        assert_eq!(skill.transitive_tokens, 150);
        assert_eq!(skill.refs.commands, vec!["git"]);
        assert!(skill.refs.paths.is_empty());
        assert!(skill.refs.urls.is_empty());
        let frag = loaded.fragments.get("check-adrs").unwrap();
        assert_eq!(frag.tokens, 42);
    }
}
